#pragma once
#include <vector>

// Placeholder: this file will be generated by tools/train_export.py (or train_export.py + export)
// Small demo network (input 5 -> hidden 8 -> output 2)
static std::vector<std::vector<float>> ML_ADDON_W = {
    { /* layer0: 8x5 */ 0.1f, -0.05f, 0.02f, 0.0f, 0.01f,
                        -0.02f, 0.03f, 0.04f, -0.01f, 0.0f,
                        0.05f, 0.01f, -0.02f, 0.03f, 0.02f,
                        0.01f, 0.01f, 0.01f, 0.01f, 0.01f,
                        -0.03f, 0.02f, 0.0f, 0.04f, -0.01f,
                        0.02f, 0.02f, -0.01f, 0.01f, 0.0f,
                        0.0f, 0.0f, 0.01f, -0.02f, 0.03f,
                        0.01f, -0.01f, 0.02f, 0.0f, 0.0f },
    { /* layer1: 2x8 */ 0.02f, -0.01f, 0.03f, 0.0f, 0.01f, 0.0f, 0.0f, 0.01f,
                        -0.01f, 0.02f, -0.02f, 0.01f, 0.0f, 0.01f, 0.01f, 0.0f }
};

static std::vector<std::vector<float>> ML_ADDON_B = {
    { 0,0,0,0,0,0,0,0 },
    { 0,0 }
};

static std::vector<size_t> ML_ADDON_SIZES = { 5, 8, 2 };
static std::vector<const char*> ML_ADDON_ACTS = { "tanh", "linear" };
